version: "3.8"

services:
    books:
        image: books
        ports:
            - 8080:8080
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        links:
            - books